package Projects.guessTheNumber;

import java.util.Random;
import java.util.Scanner;
class Game{
    private int number,guesses; // the no to guess and no. of guesses
    // Constructor
    public Game(){
        Random r=new Random();
        this.number=r.nextInt(100)+1;// range 1-100;
        // nextInt(100) this will generate greatest-integer values between 0-99( as 0.92=0 and 99.9=99, since 100 is excluded and 0 is included)
        // but to exclude 0 and include 100 in the range, +1 is considered to define the range from 1-100
        this.guesses=0;
    }
    // getter for number to get it from the constructor and no setter since we will be getting the no as input and no need to change the value after input
    public int getNumber(){
        return number;
    }
    // getter and setter for guesses
    public int getGuesses(){
        return guesses;
    }
    public void setGuesses(int guesses){
        this.guesses=guesses;
    }
    // Game logic: Compare user's guess with the actual no generated by Random
    public String checkGuess(int userGuess){ // userGuess is the input no
        guesses++;
        if(userGuess==number) {
            return "Correct!";
        } else if (userGuess>number) {
            return "Too high!";
        }
        else {
            return "Too low!";
        }
    }
}
public class GTN {

    public static void main(String[] args) {
        // by using OOPS, Creating object
        Scanner sc=new Scanner(System.in);
        Game g= new Game();
        int userGuess=0; // input is 0 yet
        System.out.println("Guess the number (1 to 100)");
        while(userGuess!=g.getNumber()){
            System.out.print("Enter your Guess: ");
            userGuess=sc.nextInt(); // input
            String result=g.checkGuess(userGuess);
            System.out.println(result);
        }
        System.out.println("\n You guessed it in "+g.getGuesses()+" attempts!");

    }
}
